version: 2.1
orbs: 
  wait-for: cobli/wait-for@0.0.2
jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - checkout

      - run: yarn
      - run: yarn build

      - persist_to_workspace:
          root: ~/repo
          paths: .
  test:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - run: yarn test
  test-mainnet-fork:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - run: yarn test-mainnet-fork
  lint:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - run: yarn lint

      # Auto-commit any lint changes
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: bash .circleci/commit.sh

workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - gh-pages
                - artifacts
      - test:
          requires:
            - build
      - test-mainnet-fork:
          requires:
            - build
      - lint:
          requires:
            - build
